package com.con2b.back.model.operation;

public enum OperationColumn  {
    OPERATION_CODE,
    REPROCESS,
    CREATION_DATE,
    STATUS,
    CHANNEL,
    PROCESSOR,
    COLABORATOR,
    COLABORATOR_EMAIL,
    COLABORATOR_PHONE,
    PRODUCT_OPTION,
    ADDITIONAL_PRODUCTS,
    OPERATION_DETAILS,
    CUSTOMER,
    INSTALLATION_ADDRESS,
    SHIPPING_ADDRESS,
    DOCUMENTATION,
}
