export const data = [
    {
        id: 0, // autogenerated
        operationCode: "xxxxx", // autogenerated
        creationDate: new Date(), // autogenerated
        status: "SOME_VALUE", // autogenerated

        channel: "SOME_VALUE", // initially null
        processorId: 0, // initially null, user foreingKey, must have PROCESSOR role

        colaboratorCode: "XXX", // user foreignKey, must have COLABORATOR role
        colaboratorEmail: "something@gmail.com", // optional, only present if email is overridden
        colaboratorPhone: "+54 249 000-0000", // optional, only present if phone is overridden

        refererCode: "XXX", // user foreignKey, initially null, will be implemented later

        productOptionId: 0, // productOption foreignKey
        additionalIds: [], // array of additional foreignKeys, many to many relationship
        operationDetails: [
            {
                type: "PORTABILITY", // either NEW, PORTABILITY or EXISTING (OperationDetailsType enum)
                phone: "+54 249 000-0001", //optional, only present if type is PORTABILITY or EXISTING
                currentProvider: "Vodaphone", //optional, only present if type is PORTABILITY
                currentOwnerFirstname: "Roberto", //optional, only present if change of owner
                currentOwnerLastname: "Perez", //optional, only present if change of owner
                currentOwnerNID: "34673447", //optional only present if change of owner
            },
        ],
        customer: {
            firstname: "Julian",
            lastname: "Perez",
            NID: "45614434",
            phone: "+54 249 000-0005",
            email: "julianperez@gmail.com",
            bankAccount: "12345623135421654321654324",
            billingAddress: {
                address: "Calle 1234",
                zipCode: "7000",
                municipality: "Tandil",
                province: "Buenos Aires",
            },
        },
        installationAddress: {
            // optional, only present if installation address is different from billing address
            address: "Calle 1234",
            zipCode: "7000",
            municipality: "Tandil",
            province: "Buenos Aires",
        },
        SIMShippingAdress: {
            // optional, only present if SIM shipping address is different from billing address
            address: "Calle 1234",
            zipCode: "7000",
            municipality: "Tandil",
            province: "Buenos Aires",
        },
        documentation: [], // array of document ids, one to many
        messages: [], // to be defined, will be implemented later
    },
];
